[project]
name = "mcp-resources"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.13.1",
    "pydantic>=2.11.7",
    "uvicorn>=0.35.0",
]
