[project]
name = "second-class"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.12.2",
    "openai-agents>=0.2.4",
    "prompt-toolkit>=3.0.51",
    "uvicorn>=0.35.0",
]
